FROM oven/bun:1.2-alpine

WORKDIR /app

# Install dependencies first (cache layer)
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# Copy source
COPY . .

# Entrypoint
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Build-time NEXT_PUBLIC_* vars (baked into static bundle)
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_E2B_DOMAIN
ARG NEXT_PUBLIC_DASHBOARD_API_URL
ARG NEXT_PUBLIC_INFRA_API_URL
ARG NEXT_PUBLIC_E2B_API_URL
ARG NEXT_PUBLIC_E2B_API_KEY
ARG NEXT_PUBLIC_E2B_FORCE_HTTP
ARG NEXT_PUBLIC_INCLUDE_BILLING
ARG NEXT_PUBLIC_STRIPE_BILLING_URL
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_MOCK_DATA=0

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL \
    NEXT_PUBLIC_E2B_DOMAIN=$NEXT_PUBLIC_E2B_DOMAIN \
    NEXT_PUBLIC_DASHBOARD_API_URL=$NEXT_PUBLIC_DASHBOARD_API_URL \
    NEXT_PUBLIC_INFRA_API_URL=$NEXT_PUBLIC_INFRA_API_URL \
    NEXT_PUBLIC_E2B_API_URL=$NEXT_PUBLIC_E2B_API_URL \
    NEXT_PUBLIC_E2B_API_KEY=$NEXT_PUBLIC_E2B_API_KEY \
    NEXT_PUBLIC_E2B_FORCE_HTTP=$NEXT_PUBLIC_E2B_FORCE_HTTP \
    NEXT_PUBLIC_INCLUDE_BILLING=$NEXT_PUBLIC_INCLUDE_BILLING \
    NEXT_PUBLIC_STRIPE_BILLING_URL=$NEXT_PUBLIC_STRIPE_BILLING_URL \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
    NEXT_PUBLIC_MOCK_DATA=$NEXT_PUBLIC_MOCK_DATA

# Build production bundle (run next directly to skip the bun prebuild env-check hook)
RUN bunx next build --webpack

EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
